-- Agency School Shop: initial schema (ported from the SQLite schema in the old src/db.js).
-- Money is always integer cents. Dates are always timestamptz.
-- The Express server uses the service role key, which bypasses row level security.
-- The RLS policies below are a second layer: a signed-in user holding only the anon key
-- and their own JWT can read their own rows and nothing else, and can write nothing.

-- ---------- Tables ----------

-- One row per Supabase Auth user. Email is copied here so the server can list admins,
-- contractors and payout recipients without paging through the Auth admin API.
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null unique,
  name text not null,
  role text not null check (role in ('buyer', 'contractor', 'admin')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.packages (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  price_cents integer not null,
  contractor_pct integer not null default 40,
  active boolean not null default true
);

create table public.orders (
  id bigint generated by default as identity primary key,
  buyer_id uuid not null constraint orders_buyer_id_fkey references public.profiles (id),
  package_id bigint not null references public.packages (id),
  package_name text not null,
  status text not null default 'pending_payment'
    check (status in ('pending_payment', 'open', 'claimed', 'ready', 'approved', 'refunded', 'cancelled')),
  price_cents integer not null,
  contractor_pct integer not null,
  turnaround text not null check (turnaround in ('24h', '3d')),
  turnaround_hours integer not null,
  business_name text not null,
  domain text,
  avada_code text not null,
  notes text,
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  stripe_session_id text,
  stripe_payment_intent text,
  card_fee_cents integer not null default 0,
  open_since timestamptz,
  unclaimed_alerted_at timestamptz,
  contractor_id uuid constraint orders_contractor_id_fkey references public.profiles (id),
  claimed_at timestamptz,
  due_at timestamptz,
  reminders_sent integer not null default 0,
  buyer_reminded boolean not null default false,
  site_url text,
  admin_url text,
  wp_username text,
  pages_built integer,
  done_at timestamptz,
  auto_approve_at timestamptz,
  approved_at timestamptz,
  contractor_pay_cents integer not null default 0,
  paid_out_at timestamptz,
  dispute boolean not null default false,
  hold_reason text,
  refunded_at timestamptz
);

create table public.exclusions (
  order_id bigint not null references public.orders (id),
  contractor_id uuid not null constraint exclusions_contractor_id_fkey references public.profiles (id),
  reason text,
  created_at timestamptz not null default now(),
  primary key (order_id, contractor_id)
);

create table public.messages (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders (id),
  sender_id uuid not null constraint messages_sender_id_fkey references public.profiles (id),
  body text not null,
  created_at timestamptz not null default now()
);

create index idx_orders_status on public.orders (status);
create index idx_orders_buyer on public.orders (buyer_id);
create index idx_orders_contractor on public.orders (contractor_id);
create index idx_messages_order on public.messages (order_id);
create index idx_exclusions_contractor on public.exclusions (contractor_id);

-- ---------- Starter packages ----------

insert into public.packages (name, description, price_cents, contractor_pct) values
  ('Avada template + 5 pages', 'Avada installed on our hosting, your template applied, and 5 pages built from your intake form.', 5000, 40),
  ('Avada template + 10 pages', 'Avada installed on our hosting, your template applied, and 10 pages built from your intake form.', 9000, 40),
  ('Homepage rebuild', 'One redesigned homepage on an existing site hosted with us.', 7500, 40);

-- ---------- The claim lock ----------
-- One UPDATE decides the winner. Postgres row locking means that when two contractors
-- claim at the same instant, the second UPDATE waits, re-checks status='open', finds
-- 'claimed' and matches nothing. Returns the claimed row, or no rows if the claim lost.
create function public.claim_order(p_order_id bigint, p_user_id uuid)
returns setof public.orders
language sql
security invoker
set search_path = ''
as $$
  update public.orders o
     set status = 'claimed',
         contractor_id = p_user_id,
         claimed_at = now(),
         due_at = now() + make_interval(hours => o.turnaround_hours),
         reminders_sent = 0
   where o.id = p_order_id
     and o.status = 'open'
     and o.dispute = false
     and not exists (
       select 1 from public.exclusions e
        where e.order_id = p_order_id and e.contractor_id = p_user_id
     )
  returning o.*;
$$;

-- Only the server (service role) may call it. Otherwise any signed-in user could
-- call it through the REST API and claim a job for anyone.
revoke execute on function public.claim_order(bigint, uuid) from public, anon, authenticated;
grant execute on function public.claim_order(bigint, uuid) to service_role;

-- ---------- Row level security ----------

alter table public.profiles enable row level security;
alter table public.packages enable row level security;
alter table public.orders enable row level security;
alter table public.exclusions enable row level security;
alter table public.messages enable row level security;

-- Explicit grants, so this works whether or not the project "automatically exposes new tables".
-- The server's service role needs full access; signed-in users get read access, narrowed by the policies below.
grant usage on schema public to service_role, authenticated;
grant all on public.profiles, public.packages, public.orders, public.exclusions, public.messages to service_role;
grant usage, select on all sequences in schema public to service_role;
grant select on public.profiles, public.packages, public.orders, public.exclusions, public.messages to authenticated;

-- No policies for anon: logged-out browsers can read nothing.
-- Signed-in users can read only their own rows, and cannot write anything directly.
revoke all on public.profiles, public.packages, public.orders, public.exclusions, public.messages from anon;
revoke insert, update, delete, truncate on public.profiles, public.packages, public.orders, public.exclusions, public.messages from authenticated;

create policy "read own profile" on public.profiles
  for select to authenticated
  using (id = (select auth.uid()));

create policy "read active packages" on public.packages
  for select to authenticated
  using (active);

create policy "read own orders" on public.orders
  for select to authenticated
  using (buyer_id = (select auth.uid()) or contractor_id = (select auth.uid()));

create policy "read own exclusions" on public.exclusions
  for select to authenticated
  using (contractor_id = (select auth.uid()));

create policy "read messages on own orders" on public.messages
  for select to authenticated
  using (exists (
    select 1 from public.orders o
     where o.id = messages.order_id
       and (o.buyer_id = (select auth.uid()) or o.contractor_id = (select auth.uid()))
  ));
